#!/usr/bin/env python

""" Crude use of Root Resource List provided by Review Board's Web API.

See https://www.reviewboard.org/docs/manual/2.5/webapi/2.0/resources/root/.

"""

import requests

url = 'https://reviews.reviewboard.org'

rsp = requests.get(url + '/api/')
root = rsp.json()

review_requests = requests.get(root['links']['review_requests']['href'])

# first review request in the list of review requests
review_request = review_requests.json()['review_requests'][0]

# first diff in the list of diffs
rsp = requests.get(review_request['links']['diffs']['href'])
diffs = rsp.json()

# use the template to create the uri
uri = root['uri_templates']['diff'].format(review_request_id=review_request['id'],
                                           diff_revision=diffs['diffs'][0]['revision'])
rsp = requests.get(uri)
diff = rsp.json()

print diff['diff']['links']['self']['href']
